services:
  backend:
    build:
      context: ./backend
    container_name: doutorado-backend
    restart: unless-stopped
    ports:
      - "3000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: doutorado-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - BACKEND_INTERNAL_URL=http://backend:8000
    ports:
      - "8089:3000"
